#!/usr/bin/env python2
#!/usr/bin python2
# -*- coding: utf-8 -*-
# Versione Python 2.7.*

# Importazione

import os, sys, subprocess
from lib import Fore, Back, Style
import time
from time import strftime 

subprocess.call("clear", shell=True)

print (Fore.GREEN + " ___         _             ___                  ")
print (Fore.GREEN + "/ __|_  _ __| |_ ___ _ __ |   \ _____ __ ___ _  ")
print (Fore.GREEN + "\__ \ || (_-<  _/ -_) '  \| |) / _ \ V  V / ' \ ")
print (Fore.GREEN + "|___/\_, /__/\__\___|_|_|_|___/\___/\_/\_/|_||_|")
print (Fore.GREEN + "     |__/                                       ")
print (Fore.GREEN + "                Coded by Alexis                 ")
print (Fore.RESET)

# Impostazione
print
print "*******************"
print "*  INSTALLAZIONE  *"
print "*******************"
print
clock = strftime("%H:%M")
print "Ora esatta del sistema:",clock
print
print "[1] Sistema autenticazione 'su'"
print "[2] Sistema autenticazione 'sudo'"
print "[3] Altro sistema"
print 
print "[0] Esci"
print 
print 

try:
    select = input(": ")
    if select >= 4:
        print "Opzione non trovata!"
        raw_input("Premere un tasto per contiuare")
        os.system("./systemdown")
except NameError:
    print "Comando non valido!"
    raw_input("Premere un tasto per continuare")
    os.system("./systemdown")


# Code
def close():
	if select == 0:
		subprocess.call("clear", shell=True)
		return
close()

def debian():
	if select == 1:
		time.sleep(2)
		subprocess.call("debian/./install.sh")
		print
		print
		print (Fore.RED + "Installazione completata!")
		print (Fore.RESET)
		print
debian()

def ubuntu():
	if select == 2:
		time.sleep(2) 
		subprocess.call("ubuntu/./install.sh")
		print
		print
		print (Fore.RED + "Installazione completata!")
		print (Fore.RESET)
		print
ubuntu()

def other():
	if select == 3:
		time.sleep(2)
		subprocess.call("other_system/./install.sh")
		print
		print
		print (Fore.RED + "Installazione completata!")
		print (Fore.RESET)
		print
other()
