#!/usr/bin/env python2
#!/usr/bin python2
# -*- coding: utf-8 -*-
# Versione Python 2.7.*

# Importazione

import os, sys, subprocess
from time import strftime, sleep
from lib import Fore, Back, Style

subprocess.call("clear", shell=True)

print (Fore.GREEN + " ___         _             ___                  ")
print (Fore.GREEN + "/ __|_  _ __| |_ ___ _ __ |   \ _____ __ ___ _  ")
print (Fore.GREEN + "\__ \ || (_-<  _/ -_) '  \| |) / _ \ V  V / ' \ ")
print (Fore.GREEN + "|___/\_, /__/\__\___|_|_|_|___/\___/\_/\_/|_||_|")
print (Fore.GREEN + "     |__/                                       ")
print (Fore.GREEN + "                Coded by Alexis                 ")
print (Fore.RESET)

# Impostazione
print
print "*******************"
print "*  INSTALLAZIONE  *"
print "*******************"
print
clock = strftime("%H:%M")
print "Ora esatta del sistema:",clock
print
print "[1] Debian"
print "[2] Ubuntu"
print "[3] Altro sistema"
print 
print "[0] Esci"
print 
print 
back = 0
select = input("Selezionare numero: ")

# Code
def close():
	if select == 0:
		subprocess.call("clear", shell=True)
		return
close()

def debian():
	if select == 1:
		sleep(2)
		subprocess.call("debian/./install.sh")
		print
		print
		print (Fore.RED + "Installazione completata!")
		print (Fore.RESET)
		print
debian()

def ubuntu():
	if select == 2:
		sleep(2) 
		subprocess.call("ubuntu/./install.sh")
		print
		print
		print (Fore.RED + "Installazione completata!")
		print (Fore.RESET)
		print
ubuntu()

def other():
	if select == 3:
		sleep(2)
		subprocess.call("other_system/./install.sh")
		print
		print
		print (Fore.RED + "Installazione completata!")
		print (Fore.RESET)
		print
other()
