#!/usr/bin/env python2
#!/usr/bin python2
# -*- coding: utf-8 -*-
# Versione Python 2.7.*

# Importazione

import os, sys, subprocess
from time import strftime
from lib import Fore, Back, Style

subprocess.call("clear", shell=True)

print (Fore.GREEN + " ___         _             ___                  ")
print (Fore.GREEN + "/ __|_  _ __| |_ ___ _ __ |   \ _____ __ ___ _  ")
print (Fore.GREEN + "\__ \ || (_-<  _/ -_) '  \| |) / _ \ V  V / ' \ ")
print (Fore.GREEN + "|___/\_, /__/\__\___|_|_|_|___/\___/\_/\_/|_||_|")
print (Fore.GREEN + "     |__/                                       ")
print (Fore.GREEN + "                Coded by Alexis                 ")
print (Fore.RESET)

# Impostazione
print
print "***************"
print "*  SETTAGGIO  *"
print "***************"
print
clock = strftime("%H:%M")
print "Ora esatta del sistema:",clock
print
print "[1] Imposta Spegnimento con orario"
print "[2] Imposta Spegnimento in minuti"
print 
print "[3] Annulla comando"
print
print "[0] Esci"
print 
print 
back = 0
select = input("Selezionare numero: ")

# Code  
def close():
	if select == 0:
		subprocess.call("clear", shell=True)
		return
close()

def shutdown():
	if select == 1:
		ora = raw_input("Inserire orario: ")
		convert = "sudo shutdown -h %s"
		os.system(convert % (ora))
		print
		print
		print (Fore.RED + "Spegnimento impostato!")
		print (Fore.RESET)
		print
shutdown()

def shutdownmin():
	if select == 2:
		minuti = raw_input("Inserire i minuti: ")
		convert = "sudo shutdown -h +%s"
		os.system(convert % (minuti))
		print
		print
		print (Fore.RED + "Spegnimento impostato!")
		print (Fore.RESET)
		print
shutdownmin()

def stop():
	if select == 3:
		subprocess.call("sudo shutdown -c", shell=True)
		print
		print (Fore.RED + "Pianificazione annullata!")
		print (Fore.RESET)
		print
stop()

